name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r tools/orchestrator/requirements.txt

      - name: Install and Build Application
        working-directory: ./tools/desktop
        run: |
          npm install
          node build.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
